### ISSUE TITLE
[BUG] Cant add group in setup

### ISSUE THREAD

**Issue by wrecktify** [chris3105x/EasyPrefix#127]
# Details
Paper version git-Paper-32 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT)  (latest as of 12/3/21)

![image](https://user-images.githubusercontent.com/2549115/144700294-4eb03c53-dae0-4480-b8be-7887d2c435b8.png)

# Describe the bug
Type /ep setup, click groups, try to Add group.  Nothing happens and get a console error.
[01:34:49 ERROR]: [EasyPrefix] Exception while trying to run action for click on StaticGuiElement in slot 35 of EasyPrefix » Groups GUI!
[01:34:49 WARN]: java.lang.ExceptionInInitializerError
[01:34:49 WARN]:        at EasyPrefix-1.8.1.jar//net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491)
[01:34:49 WARN]:        at EasyPrefix-1.8.1.jar//com.christian34.easyprefix.utils.TextInput.build(TextInput.java:32)
[01:34:49 WARN]:        at EasyPrefix-1.8.1.jar//com.christian34.easyprefix.utils.UserInterface.openGroupCreator(UserInterface.java:830)
[01:34:49 WARN]:        at EasyPrefix-1.8.1.jar//com.christian34.easyprefix.utils.UserInterface.lambda$openGroupsList$9(UserInterface.java:175)
[01:34:49 WARN]:        at EasyPrefix-1.8.1.jar//de.themoep.inventorygui.InventoryGui$GuiListener.onInventoryClick(InventoryGui.java:991)
[01:34:49 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[01:34:49 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[01:34:49 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:34:49 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[01:34:49 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2750)
[01:34:49 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[01:34:49 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:13)
[01:34:49 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[01:34:49 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:34:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[01:34:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[01:34:49 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[01:34:49 WARN]:        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[01:34:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[01:34:49 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[01:34:49 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[01:34:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[01:34:49 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[01:34:49 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[01:34:49 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[01:34:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:34:49 WARN]: Caused by: java.lang.RuntimeException: Your server version isn't supported in AnvilGUI!
[01:34:49 WARN]:        at EasyPrefix-1.8.1.jar//net.wesjd.anvilgui.version.VersionMatcher.lambda$match$1(VersionMatcher.java:53)
[01:34:49 WARN]:        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[01:34:49 WARN]:        at EasyPrefix-1.8.1.jar//net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:53)
[01:34:49 WARN]:        at EasyPrefix-1.8.1.jar//net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35)
[01:34:49 WARN]:        ... 26 more

# Expected behavior
Ability to add a new group

# Screenshots
n/a

**Comment by chris3105x** [comment]
Easyprefix is not compatible with mc 1.18 right now. This will be fixed asap.

Thank you for reporting this issue!
