### ISSUE TITLE
[BUG] Commands not working properly

### ISSUE THREAD

**Issue by chris3105x** [chris3105x/EasyPrefix#20]
# Details
**Spigot Version:** issue occured on 1.16.1, probably doesn't work on any version

*please run `/ep debug` and attach a screenshot*

# Describe the bug

not working since 1.6.6

`01.08 00:11:09 [Server] INFO Shkai issued server command: /ep setprefix
01.08 00:11:09 [Server] ERROR null
01.08 00:11:09 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ep' in plugin EasyPrefix v1.6.6
01.08 00:11:09 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-130]
01.08 00:11:09 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
01.08 00:11:09 [Server] INFO Caused by: java.lang.NullPointerException: Couldn't find subcommand with name 'set'
01.08 00:11:09 [Server] INFO at com.christian34.easyprefix.commands.CommandHandler.getSubcommand(CommandHandler.java:114) ~[?:?]
01.08 00:11:09 [Server] INFO at com.christian34.easyprefix.commands.CommandHandler.onCommand(CommandHandler.java:65) ~[?:?]
01.08 00:11:09 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-130] `
_submitted by an user on spigotmc.org_

Commands `/ep setprefix/setsuffix` not working

# Expected behavior

the commands shouldn't return a NullPointerException

# Screenshots

**Comment by chris3105x** [comment]
This issue occurs if custom-layout has been disabled in config.yml.
The plugin will no longer throw an exception if this happens. Please download the latest version from spigotmy.org.
