### ISSUE TITLE
1.16.1 Plugin Not Loading

### ISSUE THREAD

**Issue by WilSwo** [chris3105x/EasyPrefix#21]
Good afternoon,

I've been enjoying your plugin for a year now. We are in the process of updating our network to 1.16.1 - I downloaded the version that was released last night (07/31/2020), and have been getting the following error when trying to load the plugin. Any advice/help would be greatly apreciated! Thank you very much!

`[16:26:29 ERROR]: Error occurred while enabling EasyPrefix v1.6.6-R1 (Is it up to date?)
java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPI.registerExpansion(Lme/clip/placeholderapi/expansion/PlaceholderExpansion;)Z
        at com.christian34.easyprefix.extensions.CustomPlaceholder.<init>(CustomPlaceholder.java:21) ~[?:?]
        at com.christian34.easyprefix.extensions.ExpansionManager.<init>(ExpansionManager.java:22) ~[?:?]
        at com.christian34.easyprefix.EasyPrefix.onEnable(EasyPrefix.java:75) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-130]        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-130]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]`

Here is a list of all the plugins currently installed (37):

CoreProtect, DragonSlayer, dynmap*, EasyPrefix, EntityDetection, Essentials, EssentialsChat, EssentialsSpawn, FarmLimiter, FlyingCarpet, Holograms, KixsChatAnnouncer, LootChest, LWC, mcMMO, Minepacks, ModReq*, Multiverse-Core, Multiverse-Portals, Orebfuscator, PermissionsEx*, PerWorldInventory, PlaceholderAPI, PlayerHeads, PremiumVanish, ProtocolLib, QuickShop, SuperbVote, SuperTrailsPro*, TAB, Towny, TownyNameUpdater, TreasureChest, VariableTime*, Vault, Votifier, XPKeeper

**Comment by chris3105x** [comment]
Hey!
The developer of PlaceholderAPI removed some functions. Please use [this ](https://www.spigotmc.org/resources/placeholderapi.6245/download?version=328837)version.

Thank you!

**Comment by chris3105x** [comment]
Fixed. Update will come later.

Thank you!
