### ISSUE TITLE
[BUG] Error Spam and unable to use plugin

### ISSUE THREAD

**Issue by lachlankm** [chris3105x/EasyPrefix#231]
# Details
**Spigot Version:** 

*please run `/ep debug` and attach a screenshot*

# Describe the bug
Just updated to EasyPrefix 1.8.9 and we got this eorror after creating a tag.

`[5:13:24 PM WARN] [EasyPrefix] An error occurred while using EasyPrefix. If you think this is an error, please report following exception to GitHub!
[5:13:24 PM WARN] [EasyPrefix] ------ ERROR ------
[5:13:24 PM WARN] java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "list" is null
[5:13:24 PM WARN] at EasyPrefix-1.8.9.jar//com.christian34.easyprefix.commands.CommandHandler.onTabComplete(CommandHandler.java:76)
[5:13:24 PM WARN] at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:141)
[5:13:24 PM WARN] at org.bukkit.command.Command.tabComplete(Command.java:93)
[5:13:24 PM WARN] at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:240)
[5:13:24 PM WARN] at org.bukkit.craftbukkit.v1_20_R1.CraftServer.tabCompleteCommand(CraftServer.java:2283)
[5:13:24 PM WARN] at org.bukkit.craftbukkit.v1_20_R1.CraftServer.tabComplete(CraftServer.java:2255)
[5:13 PM]
[5:13:24 PM WARN] at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:74)
[5:13:24 PM WARN] at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71)
[5:13:24 PM WARN] at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:602)
[5:13:24 PM WARN] at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:582)
[5:13:24 PM WARN] at net.minecraft.server.network.PlayerConnection.lambda$handleCustomCommandSuggestions$5(PlayerConnection.java:920)
[5:13:24 PM WARN] at net.minecraft.server.TickTask.run(TickTask.java:18)
[5:13:24 PM WARN] at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[5:13:24 PM WARN] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[5:13:24 PM WARN] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
[5:13:24 PM WARN] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[5:13:24 PM WARN] at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[5:13:24 PM WARN] at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)
[5:13:24 PM WARN] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)
[5:13:24 PM WARN] at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[5:13:24 PM WARN] at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1287)
[5:13:24 PM WARN] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1175)
[5:13:24 PM WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[5:13:24 PM WARN] at java.base/java.lang.Thread.run(Thread.java:833)
[5:13:24 PM WARN] [EasyPrefix] ------ END OF ERROR ------`

# Expected behavior
For this not to happen.

# Screenshots
![image](https://github.com/chris3105x/EasyPrefix/assets/40618678/b4650404-1cb2-4dfc-8f9a-ecd8f273aae5)

**Comment by chris3105x** [comment]
With which command does this error occur?

**Comment by lachlankm** [comment]
I have manged to get it with
`/ep tags help`
`/tags list`

I just wanted to add that I also somtimes get:
`[EasyPrefix] Task #51939 for EasyPrefix v1.8.9 generated an exception`
When running `/ep settings`

**Comment by chris3105x** [comment]
fixed. thank you!
