### ISSUE TITLE
Access denied for user 'username'@'localhost'

### ISSUE THREAD

**Issue by progamerx333** [chris3105x/EasyPrefix#48]
After few minutes of working with tags, I've noticed that every one of them disappeared, even though I was able to update database earlier. Also, my database is stored on another server and the config was changed properly (otherwise it wouldn't update ranks).

> [EasyPrefix] Access denied for user 'username'@'localhost'
[EasyPrefix] Please check if the sql server is running and you entered the right username and password.
[EasyPrefix] Plugin EasyPrefix v1.7.5 generated an exception while executing task 22641
java.lang.NullPointerException: null
at com.christian34.easyprefix.sql.SelectQuery.prepareStatement(SelectQuery.java:107) ~[?:?]
at com.christian34.easyprefix.sql.SelectQuery.retrieveData(SelectQuery.java:61) ~[?:?]
at com.christian34.easyprefix.sql.SelectQuery.getData(SelectQuery.java:55) ~[?:?]
at com.christian34.easyprefix.sql.database.SQLSynchronizer.getIdFromDatabase(SQLSynchronizer.java:56) ~[?:?]
at com.christian34.easyprefix.sql.database.SQLSynchronizer.lambda$startTimer$0(SQLSynchronizer.java:43) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-401]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-401]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-401]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by chris3105x** [comment]
It would be easier and more efficient to deal with issue reports using the templates provided.
The login information was probably changed without completely restarting the server. 
An issue with the SqlSynchronizer was already reported and will be fixed within the next release.

Thank you for the report.

greetings
